### PR TITLE
Global declaration in extracted method

### PR DESCRIPTION
**Pull request by climbus**
316

Added support for global expression.

- [x] test task list checker

### CODE REVIEW

**Comment by climbus** [comment]
@lieryan Can you tell me why task is failing? Thanks

**Comment by lieryan** [comment]
It shouldn't fail. That's a new Github Actions I added recently to enforce that all [task list](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists) must be checked before merging. Your PR doesn't contain any task list, so it should not have failed; it seemed to be failing because of an unrelated issue because the task list don't have permission to access your fork or something like that.

I'll try and see if there's other different task list plugins that doesn't fail in such situations.

**Comment by climbus** [comment]
Same here https://github.com/python-rope/rope/pull/391

**Comment by lieryan** [comment]
Hi @climbus, I made [some changes](https://github.com/python-rope/rope/commit/558d69b8ede4b6e912d27f78c26248fcf8172b80) to Github Actions that should hopefully resolve the task-completed-checker issue. Can you check if this issue is still there after you pull the latest master into this branch?

**Comment by climbus** [comment]
! [remote rejected]   global_declaration -> global_declaration (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/task-completed-checker-action.yml` without `workflow` scope)

**Comment by lieryan** [comment]
Hi thanks for trying that out. Can you try rebasing this branch on top of the latest `master` and then using force push, something like this:

```
$ git fetch
$ git rebase origin/master global_declaration --onto origin/master
# ... resolve any rebase conflicts ...
$ git push --force
```

**Comment by climbus** [comment]
Unfortunately still errors
 ! [remote rejected]   global_declaration -> global_declaration (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/task-completed-checker-action.yml` without `workflow` scope)

 ! [remote rejected]   master -> master (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/task-completed-checker-action.yml` without `workflow` scope)

**Comment by lieryan** [comment]
Can you try if making a new pull request from the rebased branch works?

**Review by lieryan — APPROVED** [review]

**Comment by climbus** [comment]
> Can you try if making a new pull request from the rebased branch works?

After rebase I can't push any commit in any branch on my fork. When I  remove task check file, I can push again.

**Comment by climbus** [comment]
> > Can you try if making a new pull request from the rebased branch works?
> 
> After rebase I can't push any commit in any branch on my fork. When I remove task check file, I can push again.

Ok forget it. I had wrong permissions on token. Now it works fine. Thanks for help.

**Comment by lieryan** [comment]
Hi @climbus, great work on this one as usual :100:

**Pull request merged**
