### PR TITLE
Use inheritance instead of proxying default filesystem actions

### PR DESCRIPTION
**Pull request by soupytwist**
Enables more code sharing across fscommands implementations.

### CODE REVIEW

**Comment by soupytwist** [comment]
@mcepl, @aligrudi, can someone please review?

**Comment by mcepl** [comment]
Not sure how it relates, but a run on my RHEL-7 (python 2.7) fails:
```
======================================================================
FAIL: test_time_in_std_mods (ropetest.builtinstest.BuiltinModulesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matej/archiv/knihovna/repos/rope/ropetest/builtinstest.py", line 503, in test_time_in_std_mods
    self.assertTrue('time' in rope.base.stdmods.standard_modules())
AssertionError: False is not true

======================================================================
FAIL: test_sorting_imports_and_standard_modules2 (ropetest.refactor.importutilstest.ImportUtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matej/archiv/knihovna/repos/rope/ropetest/refactor/importutilstest.py", line 775, in test_sorting_imports_and_standard_modules2
    self.import_tools.sort_imports(pymod))
AssertionError: 'import sys\nimport time\n' != u'import sys\n\nimport time\n'

----------------------------------------------------------------------
Ran 1606 tests in 17.293s

FAILED (failures=2, skipped=4)
```

**Comment by soupytwist** [comment]
Interesting. I don't think it is related to this change, let's open a separate issue for it.

Also, I see your output `Ran 1606 tests` where on my machine runs only 1600 tests-- and the tests which failed for you pass for me, and the same on travis. Are you sure you are working on the right branch? If so maybe there is some problem with pycompat detection.

**Comment by mcepl** [comment]
> Also, I see your output Ran 1606 tests where on my machine runs only 1600 tests-- and the tests which failed for you pass for me, and the same on travis. Are you sure you are working on the right branch? If so maybe there is some problem with pycompat detection.

Here is the output from ``python setup.py clean build test`` in [tests-log.txt](https://github.com/python-rope/rope/files/503716/tests-log.txt).

Also, it is on 5c76244 (commit “Use inheritance instead of proxying default filesystem actions”) on top of 66a5612 (which is my current ``master``).

**Comment by soupytwist** [comment]
Okay. This branch was based a few commits behind master, explains the few extra tests which didn't run. This doesn't affect the tests which failed for you though, so I'm not going to block this PR on it. I opened #183 to investigate your issue... maybe something RHEL-specific?

If no problems with this commit, I'll merge. Thanks for the info!

**Comment by mcepl** [comment]
> explains the few extra tests which didn't run

You are REMOVING tests? Why?

**Comment by soupytwist** [comment]
Nothing is removed! The branch I pushed was based a few commits behind master, so was missing a commit where tests were added. Rebased. Sorry for the misunderstanding!

**Comment by mcepl** [comment]
There is no objection from me (see my comment on #183), but I would like to hear something from @aligrudi .

**Comment by emacsway** [comment]
@soupytwist , as I see, you are done refactoring method "[Replace Delegation with Inheritance](http://refactoring.com/catalog/replaceDelegationWithInheritance.html)". All arguments related to this method are present on page 355 of "Refactoring" book by Martin Fowler (as I see on right site of page by link).

Btw, great article Inheritance vs Composite "[Why extends is evil](http://www.javaworld.com/article/2073649/core-java/why-extends-is-evil.html)".

I'm not sure, that relation between classes SubversionCommands and SubversionCommands has type "[Is a](https://en.wikipedia.org/wiki/Is-a)".

**Comment by mcepl** [comment]
I am not sure how the previous comment relates to this issue (which I can still reproduce with ``master``).

**Comment by emacsway** [comment]
@mcepl , what issue do you mean? Can you give me ticket ID or any other info? My comment related to replace Delegation with Inheritance.

**Comment by emacsway** [comment]
I just give a few arguments advocated delegation, because relation "[Has a](https://en.wikipedia.org/wiki/Has-a)" looks like more appropriate in this case. I think, composition is more appropriate here than inheritance.

**Comment by mcepl** [comment]
I am sorry, I misread this ticket ... it is actually not about https://github.com/python-rope/rope/pull/182#issuecomment-250682940 (or #183). So, it is irrelevant for this ticket.

**Comment by emacsway** [comment]
@soupytwist , suppose, you need a several behaviour for filesystem operations in the future. For example, auto-creation backup files, or case-insensitive mode, or debug mode with logging, or support remote files by sftp/scp etc. How can you do this with inheritance?

**Comment by soupytwist** [comment]
I'm not sure how much of a concern it is for this project, but this change isn't all that important. I'll pass on this.

**Comment by emacsway** [comment]
Sure, it's not a problem in this case. I meant theoretical aspect.

**Pull request closed without merging**
