### PR TITLE
Migrate pytest.ini to pyproject.toml

### LINKED ISSUE #414: Migrate pytest.ini to pyproject.toml

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

# Description

Please include a summary of the change and which issue is fixed. 

Fixes #414 

# Checklist (delete if not relevant):

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated CHANGELOG.md
- [x] I have made corresponding changes to user documentation for new features 
- [x] I have made corresponding changes to library documentation for API changes

### CODE REVIEW

**Comment by lieryan** [comment]
Hi @gliptak, thanks for making this PR. The latest version of pytest that supports Python 2.7 unfortunately doesn't support putting configuration in pyproject.toml; so unfortunately, we'll have to keep the settings in pytest.ini until we drop Python 2.7 support officially.

**Comment by gliptak** [comment]
@lieryan would you be interested in that PR to drop already EOL `2.7` and `3.5` including soon  to be EOL `3.6`?

**Comment by lieryan** [comment]
We want to drop 2.7 eventually, we have a rudimentary deprecation plan for Python 2.7 in https://github.com/python-rope/rope/issues/400. But for the moment we still maintain support for it. So let's keep this PR open until that moment comes

**Comment by bagel897** [comment]
Maybe update this to get the latest CI?

**Comment by gliptak** [comment]
@bagel897 consider repushing as repo local branch

**Comment by bagel897** [comment]
I mean update this branch to the latest CI which is 3.7-3.11, just merge master. If not, I can make a new PR with the same stuff.

**Comment by gliptak** [comment]
@bagel897 please make a new branch

**Comment by bagel897** [comment]
Moved to #519

**Comment by lieryan** [comment]
Thanks for creating this PR @gliptak, thanks @bagel897 for updating this PR forwards.

**Pull request closed without merging**
