### PR TITLE
Add a little explanation of what _realpath function is about.

### PR DESCRIPTION
**Pull request by mcepl**
While looking at #109, I was digging into what `_realpath` is about and I thought it to be worthy to preserve this explanation.

@aligrudi , what do you think?

### CODE REVIEW

**Comment by aligrudi** [comment]
Matěj Cepl <notifications@github.com> wrote:
> While looking at #109, I was digging into what `_realpath` is about and I thought it to be worthy to preserve this explanation.
> 
> @aligrudi , what do you think?
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/python-rope/rope/pull/110

Unfortunately I do not remember the exact problem, but judging
by the comment preceding the 'cygwin' check, I agree that
it is a good idea to document it explicitly.

Thanks,
Ali

**Comment by mcepl** [comment]
Alternative would be to do something like this:
```diff
--- Lib/site-packages/pyx/filelocator.py-orig	2012-10-24 10:55:17.604624800 +0200
+++ Lib/site-packages/pyx/filelocator.py	2012-10-24 10:55:22.845624800 +0200
@@ -201,6 +201,11 @@
         else:
             return []
         full_filename = full_filenames.split("\n")[0].rstrip("\r")
+
+        # Detect Cygwin kpsewhich on Windows Python
+        if os.name == 'nt' and full_filename.startswith('/'):
+            full_filename = pycompat.popen('cygpath -w "%s"' % full_filename).read().strip()
+
         def _opener():
             try:
                 return builtinopen(full_filename, mode)
```

**Comment by aligrudi** [comment]
Matěj Cepl <notifications@github.com> wrote:
> Alternative would be to do something like this:
> ```diff
> --- Lib/site-packages/pyx/filelocator.py-orig	2012-10-24 10:55:17.604624800 +0200
> +++ Lib/site-packages/pyx/filelocator.py	2012-10-24 10:55:22.845624800 +0200
> @@ -201,6 +201,11 @@
>          else:
>              return []
>          full_filename = full_filenames.split("\n")[0].rstrip("\r")
> +
> +        # Detect Cygwin kpsewhich on Windows Python
> +        if os.name == 'nt' and full_filename.startswith('/'):
> +            full_filename = pycompat.popen('cygpath -w "%s"' % full_filename).read().strip()
> +

Since I do not know much about cygwin, I cannot make a
helpful comment.  However, executing cygpath on each
_realpath() call can be very expensive?

	Ali

**Comment by mcepl** [comment]
Probably, and I don't have any machine with Cygwin around (and not that much interest). I was just more or less think aloud. Let’s it rest and wait if somebody complains.

**Pull request merged**
