### PR TITLE
Issue 371 Extracting method to staticmethod/classmethod

### PR DESCRIPTION
**Pull request by climbus**
Added "kind" argument to "get_changes" which gets by now only option "staticmethod".

It refactors to static method if not self in extracted body.

### CODE REVIEW

**Comment by lieryan** [comment]
Thanks for the contribution. 

This looks pretty good to me so far.

**Comment by climbus** [comment]
Ok, I think I'm finished. 

I've added "kind" option to add_change and integrated partly with existing kind. I was guided by kind in PyFunction:  https://github.com/python-rope/rope/blob/master/rope/base/pyobjectsdef.py#L92 

I've added support for name prefixes: @ for classmethod and $ for staticmethod.

Please tell me how to prepare to merge. Merge to my fork master and start new pull request, or you can merge from this PR?

Can you merge with keeping author information? I'm asking because I had PR and author information gone: https://github.com/python-rope/rope/commit/0aec7eaa9e4caa8adf31bd9774b00a9bdacca42b

Of course, I'm waiting for any comments and suggestions.

**Comment by lieryan** [comment]
Hi @climbus, really great work here. 

I am just finishing my day up right now, so I'll review the pull request in more detail tomorrow, but from a brief skim, this looks great.

> Can you merge with keeping author information? I'm asking because I had PR and author information gone: 0aec7ea

Don't worry, your commit authorship information was not actually gone; the commit that you authored (and which records you as the author) is actually d6126a8, which is the second parent of the merge commit (0aec7ea):

image

The way git records a merge is by creating a new commit which has multiple ancestors, usually one of the ancestor is the commit that was previously on `master` branch and the other is the incoming commit. Looking at the history there, I can see that Git/GitHub correctly records that mcepl accepted and merged your commit while the actual changes was done by you, as shown here by `git annotate`:

Screenshot from 2021-09-14 04-30-12

**Comment by lieryan** [comment]
> you can merge from this PR

I would be able to merge directly from this PR, no special action needed from your side :)

**Review by lieryan — APPROVED** [review]

**Comment by lieryan** [comment]
Hi climbus, really awesome work here. 

I just found one bug here, if we start extracting from a staticmethod:

```
class A:
    @staticmethod
    def first_method(someargs):
        b_var = someargs + 1
```

When we do an extract method here on `someargs + 1`, then we are getting an error

> [Pymode]: error: Cannot extract staticmethod/classmethod with reference to someargs

Likewise, when extracting from classmethod:

```
class A:
    @classmethod
    def first_method(cls):
        b_var = cls.another()
```

When we want to extract method here on `cls.another()`, we get the same error above as well.

Thanks for your work on this.

**Review by lieryan — CHANGES_REQUESTED** [review]
Hi climbus, really awesome work here.

I just found one bug here, if we start extracting from a staticmethod:

class A:
    @staticmethod
    def first_method(someargs):
        b_var = someargs + 1

When we do an extract method here on someargs + 1, then we are getting an error

    [Pymode]: error: Cannot extract staticmethod/classmethod with reference to someargs

Likewise, when extracting from classmethod:

class A:
    @classmethod
    def first_method(cls):
        b_var = cls.another()

When we want to extract method here on cls.another(), we get the same error above as well.

Thanks for your work on this.

**Comment by climbus** [comment]
Thanks. I'll check it.

**Comment by climbus** [comment]
Fixed bug in self_name. And I've changed behavior if self is in body.  As you wrote, I don't raise an exception but self is added to method attrs.

**Review by lieryan — APPROVED** [review]

**Comment by lieryan** [comment]
This PR has been merged now. Thank you for the contribution.

**Comment by lieryan** [comment]
Hi @climbus, I was looking at your commits and noticed that Github doesn't seem to have linked your commits to your Github account. I did some looking around into this, and I believe the [most likely reason](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#commits) is that the email address that you used to create the commit (climbus@grupazpr.pl) are not linked to your Github account (which uses the address climbus@gmail.com). 

Once you [linked this email address to your Github account](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/adding-an-email-address-to-your-github-account), then I believe your contributions should be linked and counted correctly by Github.

Thanks again for your contribution!

**Comment by climbus** [comment]
I have got wrong email in my local repo. I don't know where and when I made a mistake. I'll make future commits with right email.
Thanks for investigation.

**Pull request merged**
