### PR TITLE
Remove functions in rope.base.ast that has functionally identical implementation in stdlib's ast

### PR DESCRIPTION
**Pull request by lieryan**
# Description

- Remove `rope.base.ast.walk()`
- Remove `rope.base.ast.get_children()`
- Remove `rope.base.ast.get_child_nodes()`

# Checklist (delete if not relevant):

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated CHANGELOG.md

### CODE REVIEW

**Comment by lieryan** [comment]
FYI, @edreamleo to simplify the discussion a bit; let's start by trying to remove unnecessary parts of `rope.base.ast`

These are legacy implementations which I suppose likely was written back when stdlib's ast didn't have these functionalities.

There's no need for rope to maintain these in `rope.base.ast`

**Comment by edreamleo** [comment]
@lieryan Good idea.

**Comment by edreamleo** [comment]
The crash occurs because of this line in `_ResultChecker._find_node` in `patchedasttest.py`:
```python
astutils.call_for_nodes(self.ast, search, recursive=True)
```
I'm confused: I don't see `patchedasttest.py` in the list of changed files for this PR.

Anyway, all unit tests pass after making these changes to `patchedasttest.py`:
- `from rope.base.ast import call_for_nodes`
- In `_find_node`, call `call_for_nodes(self.ast, search, recursive=True)`

Do you have any idea what happened?

**Comment by edreamleo** [comment]
@lieryan I like what I see at first glance. Thanks for meeting me halfway.

**Comment by edreamleo** [comment]
Another mystery.  In my original merge into ekr-reorg3 `rope.base.ast` still contained a `parse` function. With that parse function in place all tests pass.

One unit tests fails after removing (as I think I should) the `parse` function from `rope.base.ast`:

<details>

```console
====================================================== FAILURES =======================================================
____________________________________ PyCoreTest.test_syntax_errors_when_null_bytes ____________________________________

self = <ropetest.pycoretest.PyCoreTest testMethod=test_syntax_errors_when_null_bytes>

    def test_syntax_errors_when_null_bytes(self):
        mod = testutils.create_module(self.project, "mod")
        contents = b"\n\x00\n"
        file = open(mod.real_path, "wb")
        file.write(contents)
        file.close()
        with self.assertRaises(exceptions.ModuleSyntaxError):
>           self.pycore.resource_to_pyobject(mod)

ropetest\pycoretest.py:734:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
rope\base\pycore.py:141: in resource_to_pyobject
    return self.module_cache.get_pymodule(resource, force_errors)
rope\base\pycore.py:262: in get_pymodule
    result = pyobjectsdef.PyModule(
rope\base\pyobjectsdef.py:173: in __init__
    source, node = self._init_source(pycore, source, resource)
rope\base\pyobjectsdef.py:200: in _init_source
    ast_node = ast.parse(source_bytes, filename=filename)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def parse(source, filename='<unknown>', mode='exec', *,
              type_comments=False, feature_version=None):
        """
        Parse the source into an AST node.
        Equivalent to compile(source, filename, mode, PyCF_ONLY_AST).
        Pass type_comments=True to get back type comments where the syntax allows.
        """
        flags = PyCF_ONLY_AST
        if type_comments:
            flags |= PyCF_TYPE_COMMENTS
        if isinstance(feature_version, tuple):
            major, minor = feature_version  # Should be a 2-tuple.
            assert major == 3
            feature_version = minor
        elif feature_version is None:
            feature_version = -1
        # Else it should be an int giving the minor version for 3.x.
>       return compile(source, filename, mode, flags,
                       _feature_version=feature_version)
E       ValueError: source code string cannot contain null bytes

C:\Python\Python3.10\lib\ast.py:50: ValueError
=============================================== short test summary info ===============================================
FAILED ropetest/pycoretest.py::PyCoreTest::test_syntax_errors_when_null_bytes - ValueError: source code string cannot...
=============================== 1 failed, 1938 passed, 21 skipped, 5 xfailed in 25.60s ================================
```

</details>

**Comment by edreamleo** [comment]
@lieryan Fixed at 4242dc99. It was probably just a "normal merge error".

ekr-reorg3 contains calls to `ast.parse` and `rope.base.parse`. I haven't yet tried to make sense of it all. There still seems to be considerable confusion.

**Pull request merged**
