### PR TITLE
Nested with, issue 104

### PR DESCRIPTION
**Pull request by climbus**
https://github.com/python-rope/rope/issues/104

It was tricky issue and need an ugly hack.

I've added support for list of tokens. I think it is more obvious solution compared to adding pseudo object and next if condition: https://github.com/python-rope/rope/blob/master/rope/refactor/patchedast.py#L126

The tricky one was in python2, where nested with and comma separated has identical ast. 

If you have more elegant solution, feel free to send me.

### CODE REVIEW

**Comment by lieryan** [comment]
Hi @climbus, thank you for working on this.

If it will significantly simplify this ticket, then I think we should just drop support for Python 2.7.

I've been considering for a while that 0.20.0 might just be the last version of Rope to explicitly support Python 2.7. 

Python 2.7 is already EOL for quite some time and the 1% of people who still uses with Python 2.7 can just download an older version of Rope. AFAICT, 0.20.0 has covered pretty much all of Python 2.7 features, and 2.7 isn't going to grow new features any time soon :sweat_smile:. 

We'll need a Python 2.7 EOL planning to block 2.7 users from accidentally upgrading to incompatible version.

**Comment by lieryan** [comment]
I've opened https://github.com/python-rope/rope/issues/400 to start the ball rolling for dropping support for Python 2.7.

**Comment by climbus** [comment]
> If it will significantly simplify this ticket, then I think we should just drop support for Python 2.7.

By now it isn't a big problem. Few lines of code. 

I'll add my thoughts in the issue you added.

**Comment by climbus** [comment]
@lieryan could you merge this to master? I have to resolve new conflicts.

**Comment by lieryan** [comment]
Hi @climbus thanks for working on this issue. I've merged this PR with a couple additional changes.

**Pull request merged**
