### PR TITLE
Hinting function params, function return value, class attribute using function/class docstrings or PEP-0484 comments.

### PR DESCRIPTION
**Pull request by emacsway**
Similar solutions:
- https://www.jetbrains.com/pycharm/help/type-hinting-in-pycharm.html
- https://www.python.org/dev/peps/pep-0484/#type-comments
- http://www.pydev.org/manual_adv_type_hints.html
- https://jedi.readthedocs.org/en/latest/docs/features.html#type-hinting

Discussions:
- https://groups.google.com/d/topic/rope-dev/JlAzmZ83K1M/discussion
- https://groups.google.com/d/topic/rope-dev/LCFNN98vckI/discussion

Tested in unittest (integration) and doctests (utils).

### CODE REVIEW

**Comment by mcepl** [comment]
After all the passion of the discussion, @aligrudi I would need your help here, please.

**Comment by mcepl** [comment]
+1 from me, but I will wait with merge on comments from @aligrudi and anybody else who might come from the list for couple of days.

**Comment by emacsway** [comment]
I would like to hear the opinion of @aligrudi too.

**Comment by mcepl** [comment]
@aligrudi said yes, so merging.

**Comment by emacsway-qarea** [comment]
Thanks,

**Comment by emacsway** [comment]
Thanks,

**Pull request merged**
