### PR TITLE
dynamic versioning, reformat pyproject.toml, switch pytest.ini to pyproject.toml

### LINKED ISSUE #414: Migrate pytest.ini to pyproject.toml

### PR DESCRIPTION
**Pull request by bagel897**
Pulls versioning from PR + git - necessary for automatic DB upgrades
We need the tags to work first. Also reformatted the pyproject.toml. Please try versioning it yourself first and let me know if you want me to update CI to match.
replaces #450 
closes #414

### CODE REVIEW

**Comment by bagel897** [comment]
How should I leave credit for #450 - I copied it verbatim?

**Comment by lieryan** [comment]
To retain attribution, you can recreate the git commit by setting @gliptak as author. Easiest way to do this, if you're copying the commit more or less verbatim would be using `git cherry-pick`. 

Otherwise, there are some environment variables you can set when creating the commit in command line to override the author fields: https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables, set them to the value that was on the original commit.

I'm not quite sure how dynamic versioning works, I'll need to play with that a bit too see how I like them, though I would have preferred to keep as much of pyproject.toml as possible to be statically defined, to keep things simple for packaging tools. If it needs a dynamic component for the purpose of database re-generation, it should be the version number set in rope/__init__.py that have additional logic to append dirty/unreleased changes information to the version number, e.g. adding a hash there.

**Comment by bagel897** [comment]
Ok so how dynamic versioning works is:
1. If there's a git tag on the current commit, it uses that version - say v1.4.0 would map to 1.4.0
2. Otherwise, you take the previous git tag and do something with the commit number to get a unique dev tag like 1.4.0-dev12856.r204  

The first part means it'd be possible to create a tag and have automatic releases rather than have to bump the version manually. 
The second part helps for developing stuff like auto import without having to manually wipe the DB every commit. (but this isn't nessecary)
If we don't want to use dynamic versioning, then we should remove setuptools-scm from the build dependencies.

As for the attribution, I'll cherry pick it later, thanks

**Comment by lieryan** [comment]
Closing this as this is now replaced with #526.

**Pull request closed without merging**
