### PR TITLE
Rename variables in f-strings

### LINKED ISSUE #226: Support f"literal {string} interpolation" (PEP-498, Python 3.6)
Seems like `rope` does not yet support rename variables in [literal string interpolations (PEP-498)](https://www.python.org/dev/peps/pep-0498/)  (included since Python 3.6), e.g. renaming `var` in `f"this {var} is interpolated"`. Tested it with [VSCode's Python extension](https://github.com/Microsoft/vscode-python) which uses `rope` underneaths.

Simple test: Rename `abc`

```python
#!/usr/bin/env python3.6

abc = "hello"

print(f"{abc}")
```

### PR DESCRIPTION
**Pull request by orn688**
Adds support for renaming variables in PEP-498 f-strings for Python >= 3.6, using the `ast` module to parse f-strings while searching for occurrences of the variable. This resolves #226.

### CODE REVIEW

**Comment by orn688** [comment]
Oops, looks like Travis doesn't actually hit the tests I added because it doesn't have a pipeline for Python > 3.5.

**Comment by ikariwing** [comment]
Thank you @orn688 for improving this!

**Comment by soupytwist** [comment]
Sorry for the inaction on this, it fell off my radar. Thank you @ikariwing for the bump.

This looks great! I confirmed that tests are passing on 3.6.

**Comment by opethe1st** [comment]
Has this been released to pypi yet? This doesn't seem supported on the latest version - 0.14.0

**Comment by soupytwist** [comment]
Mmm no, there hasn't been a release in 9 months... will get one out asap.

**Comment by soupytwist** [comment]
Finally released in `0.16.0`... sorry for the long wait. Thanks again for contributing this!

**Pull request merged**
