### PR TITLE
#150 Refactoring. Implemented pluggable providers for type hinting.

### PR DESCRIPTION
**Pull request by emacsway**

### CODE REVIEW

**Comment by mcepl** [comment]
By swift browsing through the patch, I have only one question: I see just one test. Could we get some more tests to cover for this whole world? Or is the test coverage carried over from the previous commits?

**Comment by mcepl** [comment]
@aligrudi  ??? What do you think?

**Comment by emacsway** [comment]
@mcepl , we test behavior, not implementation. Behavior currently is unchanged. Under refactoring (not re-engineering) we don't have to change the tests.

**Comment by emacsway** [comment]
In future, it will be added providers for PEP-0484 annotations of python3. Also It will be possible to add custom providers by users (using config or [DIP](https://en.wikipedia.org/wiki/Dependency_injection)), for example, for Django models, etc.

Each new behavior will be tested.

**Comment by emacsway** [comment]
> Or is the test coverage carried over from the previous commits?

@mcepl , yes, all behavior covered by [old tests ](https://github.com/emacsway/rope/blob/2cc0fe92688b2d1d7ac9fe7c52fb5305361a4318/ropetest/type_hinting_test.py), I just renamed the module, because for now type-hinting can use not only docstrings.

New behavior will be added under #146

**Comment by soupytwist** [comment]
As @emacsway says, this behavior is already covered by tests, only the implementation has been moved around. Seeing as nothing new is introduced except making it configurable, I don't see any risk in accepting this. Thanks!

**Comment by emacsway** [comment]
We can inline IAttrProvider into IAssignmentProvider.
See https://github.com/emacsway/rope/blob/51ac587ad70e913946190b359813534a4b4a4664/rope/base/oi/soi.py#L79
and https://github.com/emacsway/rope/blob/51ac587ad70e913946190b359813534a4b4a4664/rope/base/oi/soi.py#L84

Let me fix it.

**Pull request merged**
