### PR TITLE
Fix autoimport not scanning packages recursively

### LINKED ISSUE #687: Missing symbols in autoimport.db
### Discussed in https://github.com/python-rope/rope/discussions/685

<div type='discussions-op-text'>

<sup>Originally posted by **rstcruzo** April  6, 2023</sup>
Hey everyone. I have been using rope with pylsp for a couple of days and noticed something odd. Autoimport suggestions contain my virtual env packages if I add the virtual env site-packages folder to the python_path preference. That's okay, but seems like rope does not scan all subfolders to generate autoimports.

For instance, I'm using `prompt_toolkit`, and the `prompt_toolkit.prompt` is returned by rope to auto import it, but the `prompt_toolkit.completion.Completer` is not. `prompt_toolkit.history.FileHistory` is listed too. So the behavior is inconsistent.

Seems to me that rope is not able to autoimport from folders inside the prompt_toolkit, since `completion` is a folder, `history` is a python file. Is this expected? or is there any configuration I can set to fix this?

I also checked the autoimport.db file and looks like the folders of prompt_toolkit are missing from there too.</div>

### PR DESCRIPTION
**Pull request by lieryan**
# Description

Change glob pattern in get_files() to scan site-packages recursively.

Fixes #687 

# Checklist (delete if not relevant):

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated CHANGELOG.md

### CODE REVIEW

**Comment by lieryan** [comment]
cc: @bagel897 FYI, this is an issue raised by rstcruzo in #685. I hope I didn't missing anything obvious with this fix here.

**Comment by bagel897** [comment]
Shouldn't it be **.py? That way it'll glob root directory files.

**Comment by lieryan** [comment]
Yeah, that's what I initially thought as well, but apparently, the `glob.glob()` and the `pathlib` glob doesn't really work the same.

Doing `**.py` is an error with pathlib's glob:

```python
In [5]: list(Path(".").glob("**.py"))
ValueError: Invalid pattern: '**' can only be an entire path component
```

`**/*.py` looks unintuitive, but it does actually include the root directory files:

```
In [12]: list(Path(".").glob("**/*.py"))
Out[12]: 
[PosixPath('setup.py'),
...
]
```

OTOH, for `glob.glob()` stdlib module, `**.py` is basically identical to `*.py`:

```python
In [10]: glob.glob("**.py", recursive=True)
Out[10]: ['setup.py']
```

and `**/*.py` works the same as pathlib's glob.

**Comment by bagel897** [comment]
Weird

**Pull request merged**
