### PR TITLE
Py3 migration group by commits

### PR DESCRIPTION
**Pull request by mcepl**
@sergeyglazyrindev ’s conversion to py3k commits.

### CODE REVIEW

**Comment by sergeyglazyrindev** [comment]
> Of course, this commit is useless in this branch, we have all this in #143 but it doesn't matter so much, because this will go in certainly after #143 and we can rebase on master before merging this pull request.
Certainly
I saw this wrong commit but was too lazy to revert it...

**Comment by sergeyglazyrindev** [comment]
@mcepl , I removed commit which correlates with Ivan Zakrevskiy commit regarging doc hinting as you asked but most likely because I did git forced push update, we lost comments to the commits

**Comment by mcepl** [comment]
> hey, unfortunately, in python 3.5 we still have failed tests We will work on it later.

Is it just some tests or whole lot of them? We can also keep testing and put it to the ``allow_failures``, so that at least testing runs and we can follow whether it gets worse.

**Comment by mcepl** [comment]
@aligrudi ping?

**Comment by sergeyglazyrindev** [comment]
a lot of tests
it can be postponed
it's better to do progress than nothing
And if we start now rope migration to python 3.5, fixing tests, that could
complicate merging changes, etc.
imho

On Wed, Feb 17, 2016 at 11:59 PM, Matěj Cepl <notifications@github.com>
wrote:

> hey, unfortunately, in python 3.5 we still have failed tests We will work
> on it later.
>
> Is it just some tests or whole lot of them? We can also keep testing and
> put it to the allow_failures, so that at least testing runs and we can
> follow whether it gets worse.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python-rope/rope/pull/144#issuecomment-185448788>.
>



-- 
Best, Sergey

**Comment by mcepl** [comment]
Let's take it to the list and I will suggest some strategy in open.

**Comment by sergeyglazyrindev** [comment]
Are you talking about google-groups mailing list ?

**Comment by mcepl** [comment]
@sergeyglazyrindev yes, http://thread.gmane.org/gmane.comp.python.rope/683

**Comment by sergeyglazyrindev** [comment]
@mcepl , k, I'll take a look into this discussion soon.

**Comment by mcepl** [comment]
For now closing this branch and moving (after some squashing of too small commits) it into https://github.com/python-rope/rope/tree/devel branch. Let's take a further development there. Further squashing of unnecessary commits and suggestions for rebases are welcome. Let's get this bird down!

**Pull request closed without merging**
