### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by cedspam**
improve python 3 support

### CODE REVIEW

**Comment by soupytwist** [comment]
Hi, can you please provide some context? Why is this change necessary and what problem is it solving?

Thanks

**Comment by cedspam** [comment]
I had carmap decoding errors without this change, some of the character
codes aren't available in all encoding and over 127 codes have different
meaning for different encodings.
In fact not specifying encoding while reading files with non base ascii
characters is not portable and depends on locale settings
I had to guess the correct encoding and utf8 was logical.
It may be a linked also to a problem in the way in which json encodes
strings with special characters

**Comment by mcepl** [comment]
> I had carmap decoding errors without this change,

Could you please explain to me how adding current directory to ``sys.path`` helps in decoding issues? I don't understand.

**Comment by mcepl** [comment]
@cedspam ping?

**Comment by cedspam** [comment]
sorry, for answering late and having answered off subject. Adding local dir to the search path solve some problems concerning import from local search path you may have on python3

**Comment by mcepl** [comment]
“some problems concerning import from local search path” still doesn’t explain to me why should we open sys.path to random directory where you run rope from (we are not talking about the directory where rope is located), which is a security risk.

Closing this as IHAVENOIDEAWHATSGOINGON. If you want to reopen, please, do so, but provide as with sufficient information:

* what was the goal you wanted to achieve
* what you did (exact steps)
* what you did hope to happen
* what actually happened (including all error messages, tracebacks, logs, etc. in full)

Thank you and I am sorry we are not able to help you better.

**Pull request closed without merging**
