### PR TITLE
Convert a local from-import of moved modules

### PR DESCRIPTION
**Pull request by gwelymernans**
Find all of the local imports. Then loop through them modifying them in
the source code along the way.

### CODE REVIEW

**Comment by mcepl** [comment]
What's the current status of this pull request? @gwelymernans , do you plan to react somehow on @aligrudi ’s comments?

**Comment by gwelymernans** [comment]
Oops...This fell off of my plate after an NMI came in. Yes, I plan to respond eventually. I might be able to get to it later this week.

**Comment by gwelymernans** [comment]
Ali,

VERY sorry that this is so late. I had a few questions. Re the line numbers after replacing a multiline import statement with one statement. Is there something better I can do there? I'm not sure how to readjust the line numbers of the other import statements.

I'm not sure what you mean by not passing "module_imports" into those methods. They need some information from module_imports. Maybe it would be best just not modifying module_imports, but recreating it with the changed text? Would that work? :-)

-bw

**Comment by aligrudi** [comment]
Bill Wendling <notifications@github.com> wrote:
> VERY sorry that this is so late. I had a few questions. Re the line numbers after replacing a multiline import statement with one statement. Is there something better I can do there? I'm not sure how to readjust the line numbers of the other import statements.
> 
> I'm not sure what you mean by not passing "module_imports" into those methods. They need some information from module_imports. Maybe it would be best just not modifying module_imports, but recreating it with the changed text? Would that work? :-)

Sorry for my delayed reply.  Unfortunately I remember very little
about the problem we were trying to solve and I need some time to
review our previous discussions before making a comment.  I shall
do that as soon as I find the time.

Thanks,
Ali

**Comment by aligrudi** [comment]
Bill Wendling <notifications@github.com> wrote:
> VERY sorry that this is so late. I had a few questions. Re the line numbers after replacing a multiline import statement with one statement. Is there something better I can do there? I'm not sure how to readjust the line numbers of the other import statements.

I am not sure.  Instead of deleting lines it may be possible to replace
them with empty strings, provided the new import statements require
fewer lines.  Or you may keep track of the difference between the
original and the resulting line numbers.

>> Modifying module_imports outside module_imports.py may not be a good
>> idea and it does not seem necessary: why to pass module_imports to
>> _change_local_import_statements()?  It can call get_module_imports()
>> directly and return the changed source.  Actually, I think the same
>> can be done in _change_import_statements() and also the module_imports
>> argument of _convert_from_import_statements() could be removed as
>> well.
> 
> I'm not sure what you mean by not passing "module_imports" into those methods. They need some information from module_imports. Maybe it would be best just not modifying module_imports, but recreating it with the changed text? Would that work? :-)

There seems to be some inconsistency here:

> @@ -472,6 +466,40 @@ def _change_occurrences_in_module(self, dest, pymodule=None,
>              return source
>          return None
>  
> +    def _convert_from_import_statements(self, pymodule, dest, new_name,
> +                                        module_imports):
> +        if not libutils.modname(dest):
> +          return False, pymodule
> +
> +        changed = self._change_import_statements(dest, new_name,
> +                                                 module_imports)
> +        if changed:
> +            source = module_imports.get_changed_source()
> +            source = self.tools.new_source(pymodule, source)
> +            pymodule = self.tools.new_pymodule(pymodule, source)
> +            module_imports = importutils.get_module_imports(self.project,
> +                                                            pymodule)
> +
> +        if self._change_local_import_statements(dest, module_imports):
> +            source = module_imports.get_changed_source()
> +            source = self.tools.new_source(pymodule, source)
> +            pymodule = self.tools.new_pymodule(pymodule, source)
> +            changed = True

In the first case (calling _change_import_statements()), you just
create module_imports when pymodule changes and in the second you rely
on _change_local_import_statements() to update module_imports.  For
functions that modify the source code, why not always return the
updated source (or None, if it was not changed) and create the updated
pymodule and module_imports if necessary?  However, I may be missing
something.

	Ali

**Comment by gwelymernans** [comment]
On Fri, Mar 13, 2015 at 2:22 AM Ali Gholami Rudi <notifications@github.com>
wrote:

> Bill Wendling <notifications@github.com> wrote:
> > VERY sorry that this is so late. I had a few questions. Re the line
> numbers after replacing a multiline import statement with one statement. Is
> there something better I can do there? I'm not sure how to readjust the
> line numbers of the other import statements.
>
> I am not sure. Instead of deleting lines it may be possible to replace
> them with empty strings, provided the new import statements require
> fewer lines. Or you may keep track of the difference between the
> original and the resulting line numbers.
>
> Okay.


> >> Modifying module_imports outside module_imports.py may not be a good
> >> idea and it does not seem necessary: why to pass module_imports to
> >> _change_local_import_statements()? It can call get_module_imports()
> >> directly and return the changed source. Actually, I think the same
> >> can be done in _change_import_statements() and also the module_imports
> >> argument of _convert_from_import_statements() could be removed as
> >> well.
> >
> > I'm not sure what you mean by not passing "module_imports" into those
> methods. They need some information from module_imports. Maybe it would be
> best just not modifying module_imports, but recreating it with the changed
> text? Would that work? :-)
>
> There seems to be some inconsistency here:
>
> > @@ -472,6 +466,40 @@ def _change_occurrences_in_module(self, dest,
> pymodule=None,
> > return source
> > return None
> >
> > + def _convert_from_import_statements(self, pymodule, dest, new_name,
> > + module_imports):
> > + if not libutils.modname(dest):
> > + return False, pymodule
> > +
> > + changed = self._change_import_statements(dest, new_name,
> > + module_imports)
> > + if changed:
> > + source = module_imports.get_changed_source()
> > + source = self.tools.new_source(pymodule, source)
> > + pymodule = self.tools.new_pymodule(pymodule, source)
> > + module_imports = importutils.get_module_imports(self.project,
> > + pymodule)
> > +
> > + if self._change_local_import_statements(dest, module_imports):
> > + source = module_imports.get_changed_source()
> > + source = self.tools.new_source(pymodule, source)
> > + pymodule = self.tools.new_pymodule(pymodule, source)
> > + changed = True
>
> In the first case (calling _change_import_statements()), you just
> create module_imports when pymodule changes and in the second you rely
> on _change_local_import_statements() to update module_imports. For
> functions that modify the source code, why not always return the
> updated source (or None, if it was not changed) and create the updated
> pymodule and module_imports if necessary? However, I may be missing
> something.


 Ah! I see what you mean. Why I did it this way was because
_change_import_statements was changing the lines in place. However,
_change_local_import_statements, it gets a list of the lines first, changes
them in that list, and then regenerates the pymodule inside of
module_imports.

Perhaps it shouldn't do that?

-bw

**Comment by mcepl** [comment]
@aligrudi ping? I think we are missing your response here …

**Comment by mcepl** [comment]
> Ah! I see what you mean. Why I did it this way was because _change_import_statements was changing the lines in place. However, _change_local_import_statements, it gets a list of the lines first, changes them in that list, and then regenerates the pymodule inside of module_imports. Perhaps it shouldn't do that?

@aligrudi reping?

**Comment by aligrudi** [comment]
Matěj Cepl <notifications@github.com> wrote:
> > Ah! I see what you mean. Why I did it this way was because _change_import_statements was changing the lines in place. However, _change_local_import_statements, it gets a list of the lines first, changes them in that list, and then regenerates the pymodule inside of module_imports. Perhaps it shouldn't do that?
> 
> @aligrudi reping?

I am afraid I remember almost nothing about this issue
(I guess the section of my memory used for storing the
discussions about this issue--and who knows what more--must
have been reset).  Thus, I can only say that if there is
some inconsistency there, it would be great to fix it.

Thanks,
Ali

**Comment by mcepl** [comment]
@gwelymernans this situation is clearly unfortunate. Could you please though recheck once more what you are doing to make sure we are not merging something obviously wrong?

**Comment by mcepl** [comment]
OK, I don't understand this pull request and I don't get much feedback on it. If you have something nice to say about, let me know and I can reopen it. Meanwhile, this is closed.

**Pull request closed without merging**
