### PR TITLE
Relicensing to LGPLv3+

### LINKED ISSUE #262: Relicense rope under LGPL
Given https://github.com/Microsoft/vscode-python/issues/3867 I would like to consider relicensing whole ``rope`` project under another license more accessible to editors/IDE desiring to use rope.

It is not only attempt to butter VS Code developers up, but truly plain GPL doesn't make sense much for the project, which is essentially a library. Despite what [some others say](https://www.gnu.org/philosophy/pragmatic.html), I don't think tricking somebody into free software by spreading infection is not The Right Thing to do, and so I would prefer to relicense under an non-infectious license.

The question remains which license to use. In order to lessen friction (and because I like it), I would suggest [LGPL3+](https://www.gnu.org/licenses/lgpl.html) because it is the up-to-date version closest to the current license, and thus hopefully least controversial.

I would like to ask all you listed below add a comment with your agreement (just +1 is enough, but please make a separate comment so we have record of your name) if you agree with this change to LGPL3+. If you don't agree or if you really want a different license, please, make a comment as well. Of course, I give my +1 by filing this issue now.

This list should be hopefully list of all people who have more than two commits in the tree. If you are a committer and you are not listed below, please, let us know as well.

Thank you.

- [ ] @abingham
- [ ] @aligrudi
- [ ] @brendanator
- [ ] @digenis
- [x] @dsyzling
- [x] @emacsway
- [x] @enomado
- [x] @ferada
- [x] @gwelymernans
- [x] @hayd
- [x] @hpapaxen
- [x] @jorgenschaefer
- [ ] @MarekLew
- [x] @mcepl 
- [x] @orestis
- [x] @piranha
- [x] @sergeyglazyrindev
- [x] @soupytwist
- [x] @stpierre
- [x] @tzing

### PR DESCRIPTION
**Pull request by mcepl**
Fixes #262

Please, review and comment swiftly.

### CODE REVIEW

**Comment by soupytwist** [comment]
Matej, I'm sorry for the slowness on this. I have been on vacation for the past week and fairly disconnected. I would have preferred to receive explicit permission from @aligrudi before going ahead with this, but seeing as he is unresponsive and you have issued many notices about this, I think we only can proceed with this. Thank you for your effort.

**Comment by mcepl** [comment]
@soupytwist I was slow to react. I was harshly promising merge without mercy and then I got distracted :(. Yes, I would love @aligrudi 's reaction as well, but he apparently got lost in the bowls of history. If he sues us, we will have to rewrite good part of rope, but I hope he won't.

**Comment by mcepl** [comment]
So, we should release now, shouldn't we?

**Comment by soupytwist** [comment]
0.14.0 is released.

**Pull request merged**
