### PR TITLE
Initial work towards python 3

### PR DESCRIPTION
**Pull request by hayd**
I realise that some others may have done some work in this direction cc #57.

This changes syntax and imports so that python at least runs (while tests continue to pass in python 2).

### CODE REVIEW

**Comment by mcepl** [comment]
Otherwise when running `python setup.py test` on your pull request I get in the end of the log this:
```
======================================================================
ERROR: test_encoding_declaration_in_the_second_line (ropetest.projecttest.ProjectTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matej/archiv/knihovna/repos/rope/ropetest/projecttest.py", line 416, in test_encoding_declaration_in_the_second_line
    self.assertEquals(contents, sample_file.read().encode('latin-1'))
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/resources.py", line 113, in read
    raise exceptions.ModuleDecodeError(self.path, e.reason)
ModuleDecodeError: Cannot decode file <my_file.txt>: invalid start byte

======================================================================
ERROR: test_using_utf8_when_writing_in_case_of_errors (ropetest.projecttest.ProjectTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matej/archiv/knihovna/repos/rope/ropetest/projecttest.py", line 407, in test_using_utf8_when_writing_in_case_of_errors
    sample_file.write(contents)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/resources.py", line 125, in write
    'Writing file <%s>' % self.path)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/resources.py", line 99, in _perform_change
    self.project.do(changes)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/project.py", line 116, in do
    self.history.do(changes, task_handle=task_handle)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/history.py", line 36, in do
    changes.do(change.create_job_set(task_handle, changes))
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/change.py", line 65, in do
    change.do(job_set)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/change.py", line 126, in call
    function(self)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/change.py", line 150, in do
    self._operations.write_file(self.resource, self.new_contents)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/change.py", line 331, in write_file
    data = rope.base.fscommands.unicode_to_file_data(contents)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/fscommands.py", line 198, in unicode_to_file_data
    encoding = read_str_coding(contents)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/fscommands.py", line 248, in read_str_coding
    source = source.decode("utf-8")
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xef' in position 1: ordinal not in range(128)

======================================================================
ERROR: test_file_encoding_reading (ropetest.pycoretest.PyCoreTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matej/archiv/knihovna/repos/rope/ropetest/pycoretest.py", line 424, in test_file_encoding_reading
    mod.write(contents)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/resources.py", line 125, in write
    'Writing file <%s>' % self.path)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/resources.py", line 99, in _perform_change
    self.project.do(changes)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/project.py", line 116, in do
    self.history.do(changes, task_handle=task_handle)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/history.py", line 36, in do
    changes.do(change.create_job_set(task_handle, changes))
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/change.py", line 65, in do
    change.do(job_set)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/change.py", line 126, in call
    function(self)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/change.py", line 150, in do
    self._operations.write_file(self.resource, self.new_contents)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/change.py", line 331, in write_file
    data = rope.base.fscommands.unicode_to_file_data(contents)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/fscommands.py", line 198, in unicode_to_file_data
    encoding = read_str_coding(contents)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/fscommands.py", line 248, in read_str_coding
    source = source.decode("utf-8")
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xef' in position 25: ordinal not in range(128)

======================================================================
ERROR: test_no_exceptions_on_module_encoding_problems (ropetest.pycoretest.PyCoreTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matej/archiv/knihovna/repos/rope/ropetest/pycoretest.py", line 568, in test_no_exceptions_on_module_encoding_problems
    mod.read()
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/resources.py", line 113, in read
    raise exceptions.ModuleDecodeError(self.path, e.reason)
ModuleDecodeError: Cannot decode file <mod.py>: invalid start byte

======================================================================
ERROR: test_get_pydoc_unicode (ropetest.contrib.codeassisttest.CodeAssistTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matej/archiv/knihovna/repos/rope/ropetest/contrib/codeassisttest.py", line 491, in test_get_pydoc_unicode
    doc = get_doc(self.project, src, src.index('foo') + 1)
  File "/home/matej/archiv/knihovna/repos/rope/rope/contrib/codeassist.py", line 64, in get_doc
    pyname = fixer.pyname_at(offset)
  File "/home/matej/archiv/knihovna/repos/rope/rope/contrib/fixsyntax.py", line 51, in pyname_at
    pymodule = self.get_pymodule()
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/utils.py", line 11, in _wrapper
    setattr(self, name, func(self, *args, **kwds))
  File "/home/matej/archiv/knihovna/repos/rope/rope/contrib/fixsyntax.py", line 32, in get_pymodule
    force_errors=True)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/libutils.py", line 94, in get_string_module
    force_errors=force_errors)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/pyobjectsdef.py", line 156, in __init__
    source, node = self._init_source(pycore, source, resource)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/pyobjectsdef.py", line 180, in _init_source
    source_bytes = fscommands.unicode_to_file_data(source_code)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/fscommands.py", line 198, in unicode_to_file_data
    encoding = read_str_coding(contents)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/fscommands.py", line 248, in read_str_coding
    source = source.decode("utf-8")
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-36: ordinal not in range(128)

======================================================================
ERROR: test_get_pydoc_utf8_bytestring (ropetest.contrib.codeassisttest.CodeAssistTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matej/archiv/knihovna/repos/rope/ropetest/contrib/codeassisttest.py", line 497, in test_get_pydoc_utf8_bytestring
    doc = get_doc(self.project, src, src.index('foo') + 1)
  File "/home/matej/archiv/knihovna/repos/rope/rope/contrib/codeassist.py", line 64, in get_doc
    pyname = fixer.pyname_at(offset)
  File "/home/matej/archiv/knihovna/repos/rope/rope/contrib/fixsyntax.py", line 51, in pyname_at
    pymodule = self.get_pymodule()
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/utils.py", line 11, in _wrapper
    setattr(self, name, func(self, *args, **kwds))
  File "/home/matej/archiv/knihovna/repos/rope/rope/contrib/fixsyntax.py", line 32, in get_pymodule
    force_errors=True)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/libutils.py", line 94, in get_string_module
    force_errors=force_errors)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/pyobjectsdef.py", line 156, in __init__
    source, node = self._init_source(pycore, source, resource)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/pyobjectsdef.py", line 180, in _init_source
    source_bytes = fscommands.unicode_to_file_data(source_code)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/fscommands.py", line 198, in unicode_to_file_data
    encoding = read_str_coding(contents)
  File "/home/matej/archiv/knihovna/repos/rope/rope/base/fscommands.py", line 248, in read_str_coding
    source = source.decode("utf-8")
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 30-39: ordinal not in range(128)

----------------------------------------------------------------------
Ran 1555 tests in 8.288s

FAILED (errors=6)
Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    'test': RunTests,
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 27, in run
    sys.exit(0 if results.wasSuccessful() else 1)
NameError: global name 'sys' is not defined
```
I am not sure whether it is all just `unittest` v. `nose` problem (for that see above), but this really should work.

Generally, I **REALLY** like this pull request (@aligrudi?) and I think it is a good step towards future, and I hope that we can make it working. Correct error returns from `python setup.py test` is resolvable issue (I resolved it once somewhere, but not sure what I did right now, I will take a look and report here if I found it).

**Comment by hayd** [comment]
I'll change the nosetests back, that's fine (I missed the sys import, but with that the error code works).

Will see if I can fix the failing tests (which aren't seen by nosetests!!!)

**Comment by mcepl** [comment]
If you `git rebase -i master` and reorganize those commits into something nicer, I'll merge the result.

**Comment by hayd** [comment]
@mcepl great! Sorry I added a few fixes at the end and forgot to clean up. I've rebased, and reordered some of this (it's now: one commit for futurize stage 1, one for misc. py3 clean up, one for travis tests).

Note results on py3:
```
Ran 1555 tests in 7.855s
FAILED (failures=93, errors=189)
```
Most are actual assertion errors. *There's a couple of SyntaxErrors (due to exec-ing py2 syntax in the tests, not sure what to do there - maybe skip in py3 / and add copy of the test with the new syntax) and one "can't insert into a range" (which is an easy fix).*

**Comment by mcepl** [comment]
> Most are actual assertion errors. There's a couple of SyntaxErrors (due to exec-ing py2 syntax in the tests, not sure what to do there - maybe skip in py3 / and add copy of the test with the new syntax) and one "can't insert into a range" (which is an easy fix).

Let's deal with this latter. No, I am afraid rope when running should be able to work with py2 code and vice versa. Why do we **execute** the analyzed code? Seems wrong (even for the security reasons).

@aligrudi ?

**Comment by hayd** [comment]
Thanks for the merge.

This were the SyntaxError tests I was describing (not sure if this was all of them) https://github.com/hayd/rope/commit/1907aba6803f5a12b63455a745209a43e5cf3553 (IIRC these are exec or execfiled somewhere, hence the SyntaxError).

**Comment by aligrudi** [comment]
Matěj Cepl <notifications@github.com> wrote:
> > Most are actual assertion errors. There's a couple of SyntaxErrors (due to exec-ing py2 syntax in the tests, not sure what to do there - maybe skip in py3 / and add copy of the test with the new syntax) and one "can't insert into a range" (which is an easy fix).
> 
> Let's deal with this latter. No, I am afraid rope when running should be able to work with py2 code and vice versa. Why do we **execute** the analyzed code? Seems wrong (even for the security reasons).
> 
> @aligrudi ?

I agree: If the failing tests can be modified slightly to work
in both py2 and py3, I suggest just doing that.  Otherwise, I
too suggest cloning them for py3 and adding the necessary
decorators to ensure that they are executed in proper python
versions.

Sorry about my delayed reply.

Thanks,
Ali

**Pull request merged**
